### ISSUE TITLE
Code of coduct: clarify "following online"

### ISSUE THREAD

**Issue by lsalvadore** [ProtonMail/.github#1]
According to the code of conduct, the following is unacceptable behavior:
"Deliberate intimidation, stalking or following (online or in person)."

I don't think you mean that it is unacceptable behavior to follow online someone on GitHub or on any social network using the intended platform functionalities, do you? If indeed you don't, I suggest you to clarify this point (I would either remove the verb "following" or explicitely state that following on GitHub and social networks is ok).

**Comment by bartbutler** [comment]
Most certainly we do not. Thanks for pointing that out.

**Comment by kwojwaj** [comment]
@lsalvadore thank you for your comment. I have update the code of conduct.
